import UIKit
import CoreGraphics

/// Orchestrates the execution of all skin-metric analyzers for a single facial zone.
///
/// `SkinMetricEngine` runs every registered `SkinMetricAnalyzer` against the supplied
/// image and masks, aggregating the individual scores into a zone-level dictionary.
enum SkinMetricEngine {

    /// The complete set of cosmetic metric analyzers.
    static let allAnalyzers: [SkinMetricAnalyzer] = [
        RednessAnalyzer(),
        TextureAnalyzer(),
        SpotAnalyzer(),
        PigmentationAnalyzer(),
        ShineAnalyzer(),
        DrynessAnalyzer(),
        EvennessAnalyzer()
    ]

    /// Runs all analyzers on the given zone and returns a keyed dictionary of scores.
    ///
    /// - Parameters:
    ///   - zone: The facial zone being analysed (used for logging / debugging only;
    ///     the metric implementations themselves are zone-agnostic).
    ///   - image: The source facial image.
    ///   - skinMask: Optional global skin mask generated by `SkinMaskGenerator`.
    ///   - zoneMask: Optional mask isolating the specific facial zone.
    /// - Returns: A dictionary mapping each `SkinMetricKey` to its computed `SkinMetricScore`.
    static func analyzeZone(
        zone: SkinZone,
        image: UIImage,
        skinMask: CGImage?,
        zoneMask: CGImage?
    ) -> [SkinMetricKey: SkinMetricScore] {
        var results: [SkinMetricKey: SkinMetricScore] = [:]
        results.reserveCapacity(allAnalyzers.count)

        for analyzer in allAnalyzers {
            let score = analyzer.analyze(
                image: image,
                skinMask: skinMask,
                zoneMask: zoneMask
            )
            results[analyzer.metricKey] = score
        }

        return results
    }
}
